### PR TITLE
Compiler Promotion: Update LLVM/SPIRV/Hipify Submodules (Nov24 -> Jan05)

### PR DESCRIPTION
**Pull request by lajagapp**
## Overview

This PR updates the compiler submodules for TheRock build:
- `amd-llvm` submodule
- `hipify` submodule  
- `spirv-llvm-translator` submodule
- Removed `patches/amd-mainline/llvm-project/0003-HACK-Handle-ROCM-installation-layout-of-lib-llvm-bin.patch`

## Submodule Updates

| Submodule | Current Commit | New Commit |
|-----------|----------------|------------|
| amd-llvm | `985b939` | `3123662` |
| hipify | `d59429d` | `a6338cc` |
| spirv-llvm-translator | `0eaeb11` | `3bceafa` |

### Commit Ranges

- **amd-llvm**: [ROCm/llvm-project@985b939...3123662](https://github.com/ROCm/llvm-project/compare/985b939...3123662)
- **hipify**: [ROCm/hipify@d59429d...a6338cc](https://github.com/ROCm/hipify/compare/d59429d...a6338cc)
- **spirv-llvm-translator**: [ROCm/SPIRV-LLVM-Translator@0eaeb11...3bceafa](https://github.com/KhronosGroup/SPIRV-LLVM-Translator/compare/0eaeb11...3bceafa)
- **Removed 0003-HACK-Handle-ROCM-installation-layout-of-lib-llvm-bin.patch**: This patch is removed since related llvm change available as part of this llvm promotion (https://github.com/ROCm/llvm-project/commit/8871e9e2e2c0941b04b22f719906a588fe523be2 - Nov27 commit)

Time Period: November 24, 2025 → January 05, 2026

### LLVM Version Information
Base Version: clang version 22.0.0
Major Version Change: No

## Test Plan

- Full TheRock build (Linux & Windows)
- PyTorch build with new compiler

## Test Results

- Full Linux build - https://github.com/ROCm/TheRock/actions/runs/21662585072 - SUCCESS
- Full Windows build - https://github.com/ROCm/TheRock/actions/runs/21662604099 - SUCCESS
- PyTorch build with new compiler
https://github.com/ROCm/TheRock/actions/workflows/release_portable_linux_pytorch_wheels.yml?query=branch%3Ausers%2Flajagapp%2Fcompiler-jan05-promo

### CODE REVIEW

**Comment by lajagapp** [comment]
> CI looks good, however checking for the patch deletion, I noticed that the PR description is misleading.
> 
> The PR description says diff should be `ROCm/llvm-project@985b939...a0ab125` but links to [ROCm/llvm-project@985b939...63a5e6d](https://github.com/ROCm/llvm-project/compare/985b939...63a5e6d). Commit `a0ab125` (also noted in the table) seems not be on the llvm-project repo.
> 
> Please fix this and re-request a review afterwards. Furthermore, some PyTorch builds are failing but I am not sure if those build failures are pre-existing or due to the compiler promotion.

I've updated the PR description with patch deletion details.

> **Removed 0003-HACK-Handle-ROCM-installation-layout-of-lib-llvm-bin.patch:** This patch is removed since related llvm change available as part of this llvm promotion ([ROCm/llvm-project@8871e9e](https://github.com/ROCm/llvm-project/commit/8871e9e2e2c0941b04b22f719906a588fe523be2) - Nov27 commit)



Since a0ab125 is merge commit, diff doesn’t work with [ROCm/llvm-project@985b939...a0ab125](https://github.com/ROCm/llvm-project/compare/985b939...a0ab125), so updated the link with 63a5e6d (HEAD commit of this merge PR/commit a0ab125).

Now, I’ve updated the llvm submodule with following commits included and updated the PR description and started the full TheRock build.
```
3123662d3ea2 2026-02-06 10:02:10 -0500  Cherry-pick ea32b336 from amd-staging (#1368)
75d3e7621da0 2026-02-04 22:51:24 -0500  Cherry-picks: 61f272d and be9ba44 to amd-mainline (#1351)
6f7f6c567eeb 2026-02-04 18:06:58 -0500  Revert "AMDGPU: Fix runtime unrolling when cascaded GEPs present (#147700) (#1349)
b233f4cea18c 2026-02-04 17:25:15 +0000  [AMDGPU] Add machineFunctionInfo to recent MIR tests (#179602)
4bf1d207e402 2026-02-04 15:01:32 +0000  [AMDGPU] Pre-GFX10 does not need added latency for workgroup fences (#177157)
a0ab125feef2 2026-02-04 00:00:52 -0500  Bulk Promotion from 2026 01 05 (#1325)
```
https://github.com/ROCm/TheRock/actions/runs/21867546224
https://github.com/ROCm/TheRock/actions/runs/21867552352

**Comment by lajagapp** [comment]
Fix for Pytorch compilation failure on gfx110X is also included in latest submodule update.
gfx110X - https://github.com/ROCm/TheRock/actions/runs/21671253952/job/62479458350
Fix - https://github.com/ROCm/llvm-project/pull/1368/changes/ea32b336251c08b84eea92aa4560edad43e26a44

**Comment by lajagapp** [comment]
> > * PyTorch build with new compiler
> >   https://github.com/ROCm/TheRock/actions/workflows/release_portable_linux_pytorch_wheels.yml?query=branch%3Ausers%2Flajagapp%2Fcompiler-jan05-promo
> 
> Are you expecting those builds to be successful? I see mostly failures. There have been a few pytorch build failures lately that are in various stages of being fixed so I want to make sure this isn't introducing new failures.
> 
> For example: https://github.com/ROCm/TheRock/actions/runs/21876319188/job/63146097226
> 
> ```
> [17](https://github.com/ROCm/TheRock/actions/runs/21876319188/job/63146097226#step:11:49618)
> [7820/7944] Linking CXX executable bin/NamedTensor_test
> FAILED: bin/NamedTensor_test 
> : && /opt/rh/gcc-toolset-13/root/usr/bin/c++ -Wno-error=maybe-uninitialized -Wno-error=uninitialized -Wno-error=restrict -I/opt/python/cp311-cp311/lib/python3.11/site-packages/_rocm_sdk_devel/lib/rocm_sysdeps/include -I/opt/python/cp311-cp311/lib/python3.11/site-packages/_rocm_sdk_devel/include/roctracer -D_GLIBCXX_USE_CXX11_ABI=1 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOXPUPTI=ON -DUSE_FBGEMM -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=range-loop-construct -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-unknown-pragmas -Wno-unused-parameter -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-dangling-reference -Wno-error=dangling-reference -Wno-error=redundant-move -Wno-stringop-overflow -DHAVE_AVX512_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION -O3 -DNDEBUG -DNDEBUG -L/opt/python/cp311-cp311/lib/python3.11/site-packages/_rocm_sdk_devel/lib/rocm_sysdeps/lib -rdynamic     -Wl,--no-as-needed caffe2/CMakeFiles/NamedTensor_test.dir/__/aten/src/ATen/test/NamedTensor_test.cpp.o -o bin/NamedTensor_test  -Wl,-rpath,/__w/TheRock/TheRock/external-builds/pytorch/pytorch/build/lib:/opt/_internal/cpython-3.11.12/lib/python3.11/site-packages/_rocm_sdk_devel/lib:/opt/python/cp311-cp311/lib/python3.11/site-packages/_rocm_sdk_devel/lib:  lib/libgtest_main.a  -lstdc++  -Wl,--no-as-needed,"/__w/TheRock/TheRock/external-builds/pytorch/pytorch/build/lib/libtorch.so" -Wl,--as-needed  -Wl,--no-as-needed,"/__w/TheRock/TheRock/external-builds/pytorch/pytorch/build/lib/libtorch_cpu.so" -Wl,--as-needed  lib/libprotobuf.a  -Wl,--no-as-needed,"/__w/TheRock/TheRock/external-builds/pytorch/pytorch/build/lib/libtorch_hip.so" -Wl,--as-needed  lib/libc10_hip.so  lib/libc10.so  /opt/_internal/cpython-3.11.12/lib/python3.11/site-packages/_rocm_sdk_devel/lib/libMIOpen.so.1.0  /opt/python/cp311-cp311/lib/python3.11/site-packages/_rocm_sdk_devel/lib/libhiprtc.so.7.3.53390-a160f7a7d7  -ldl  /opt/_internal/cpython-3.11.12/lib/python3.11/site-packages/_rocm_sdk_devel/lib/libhipblas.so.3.3  /opt/_internal/cpython-3.11.12/lib/python3.11/site-packages/_rocm_sdk_devel/lib/libhipfft.so.0.1  /opt/_internal/cpython-3.11.12/lib/python3.11/site-packages/_rocm_sdk_devel/lib/libhiprand.so.1.1  /opt/_internal/cpython-3.11.12/lib/python3.11/site-packages/_rocm_sdk_devel/lib/librocrand.so.1.1  /opt/_internal/cpython-3.11.12/lib/python3.11/site-packages/_rocm_sdk_devel/lib/libhipsparse.so.4.3.0  /opt/_internal/cpython-3.11.12/lib/python3.11/site-packages/_rocm_sdk_devel/lib/libhipsolver.so.1.0  /opt/_internal/cpython-3.11.12/lib/python3.11/site-packages/_rocm_sdk_devel/lib/librocblas.so.5.3  /opt/python/cp311-cp311/lib/python3.11/site-packages/_rocm_sdk_devel/lib/libamdhip64.so.7.3.53390-a160f7a7d7  /opt/python/cp311-cp311/lib/python3.11/site-packages/_rocm_sdk_devel/lib/libhipblaslt.so.1.2  lib/libgtest.a  -pthread && /opt/_internal/cpython-3.11.12/lib/python3.11/site-packages/cmake/data/bin/cmake -E __run_co_compile --lwyu="ldd;-u;-r" --source=bin/NamedTensor_test && :
> /opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: /opt/_internal/cpython-3.11.12/lib/python3.11/site-packages/_rocm_sdk_devel/lib/librccl.so.1: undefined reference to `ncclSymkGetKernelPtr(ncclSymkKernelId, int, ncclDataType_t)'
> collect2: error: ld returned 1 exit status
> ```
> 
> (that looks like #3268, which was resolved... you might have chosen a commit in the broken range)

Yes, I see same rccl linking error (`undefined reference to ncclSymkGetKernelPtr(ncclSymkKernelId, int, ncclDataType_t)'`) with all the pytorch build which is triggered yesterday with this PR.
I see revert for this failure is already merged in main branch (https://github.com/ROCm/TheRock/pull/3271).
Now, I've rebased this PR with latest main branch which includes above revert and restarted the full build.
https://github.com/ROCm/TheRock/actions/runs/21898608999
https://github.com/ROCm/TheRock/actions/runs/21898615949

**Comment by marbre** [comment]
> Yes, I see same rccl linking error (`undefined reference to ncclSymkGetKernelPtr(ncclSymkKernelId, int, ncclDataType_t)'`) with all the pytorch build which is triggered yesterday with this PR.
> I see revert for this failure is already merged in main branch (#3271).
> Now, I've rebased this PR with latest main branch which includes above revert and restarted the full build.
> https://github.com/ROCm/TheRock/actions/runs/21898608999
> https://github.com/ROCm/TheRock/actions/runs/21898615949

The RCCL switch over was re-landed today but should be fine as RCCL fixed the reference error in an commit upstream which the latest rocm-systems bump in TheRock includes :)

**Comment by lajagapp** [comment]
> > > * PyTorch build with new compiler
> > >   https://github.com/ROCm/TheRock/actions/workflows/release_portable_linux_pytorch_wheels.yml?query=branch%3Ausers%2Flajagapp%2Fcompiler-jan05-promo
> > 
> > 
> > Are you expecting those builds to be successful? I see mostly failures. There have been a few pytorch build failures lately that are in various stages of being fixed so I want to make sure this isn't introducing new failures.
> > For example: https://github.com/ROCm/TheRock/actions/runs/21876319188/job/63146097226
> > ```
> > [17](https://github.com/ROCm/TheRock/actions/runs/21876319188/job/63146097226#step:11:49618)
> > [7820/7944] Linking CXX executable bin/NamedTensor_test
> > FAILED: bin/NamedTensor_test 
> > : && /opt/rh/gcc-toolset-13/root/usr/bin/c++ -Wno-error=maybe-uninitialized -Wno-error=uninitialized -Wno-error=restrict -I/opt/python/cp311-cp311/lib/python3.11/site-packages/_rocm_sdk_devel/lib/rocm_sysdeps/include -I/opt/python/cp311-cp311/lib/python3.11/site-packages/_rocm_sdk_devel/include/roctracer -D_GLIBCXX_USE_CXX11_ABI=1 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOXPUPTI=ON -DUSE_FBGEMM -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=range-loop-construct -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-unknown-pragmas -Wno-unused-parameter -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-dangling-reference -Wno-error=dangling-reference -Wno-error=redundant-move -Wno-stringop-overflow -DHAVE_AVX512_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION -O3 -DNDEBUG -DNDEBUG -L/opt/python/cp311-cp311/lib/python3.11/site-packages/_rocm_sdk_devel/lib/rocm_sysdeps/lib -rdynamic     -Wl,--no-as-needed caffe2/CMakeFiles/NamedTensor_test.dir/__/aten/src/ATen/test/NamedTensor_test.cpp.o -o bin/NamedTensor_test  -Wl,-rpath,/__w/TheRock/TheRock/external-builds/pytorch/pytorch/build/lib:/opt/_internal/cpython-3.11.12/lib/python3.11/site-packages/_rocm_sdk_devel/lib:/opt/python/cp311-cp311/lib/python3.11/site-packages/_rocm_sdk_devel/lib:  lib/libgtest_main.a  -lstdc++  -Wl,--no-as-needed,"/__w/TheRock/TheRock/external-builds/pytorch/pytorch/build/lib/libtorch.so" -Wl,--as-needed  -Wl,--no-as-needed,"/__w/TheRock/TheRock/external-builds/pytorch/pytorch/build/lib/libtorch_cpu.so" -Wl,--as-needed  lib/libprotobuf.a  -Wl,--no-as-needed,"/__w/TheRock/TheRock/external-builds/pytorch/pytorch/build/lib/libtorch_hip.so" -Wl,--as-needed  lib/libc10_hip.so  lib/libc10.so  /opt/_internal/cpython-3.11.12/lib/python3.11/site-packages/_rocm_sdk_devel/lib/libMIOpen.so.1.0  /opt/python/cp311-cp311/lib/python3.11/site-packages/_rocm_sdk_devel/lib/libhiprtc.so.7.3.53390-a160f7a7d7  -ldl  /opt/_internal/cpython-3.11.12/lib/python3.11/site-packages/_rocm_sdk_devel/lib/libhipblas.so.3.3  /opt/_internal/cpython-3.11.12/lib/python3.11/site-packages/_rocm_sdk_devel/lib/libhipfft.so.0.1  /opt/_internal/cpython-3.11.12/lib/python3.11/site-packages/_rocm_sdk_devel/lib/libhiprand.so.1.1  /opt/_internal/cpython-3.11.12/lib/python3.11/site-packages/_rocm_sdk_devel/lib/librocrand.so.1.1  /opt/_internal/cpython-3.11.12/lib/python3.11/site-packages/_rocm_sdk_devel/lib/libhipsparse.so.4.3.0  /opt/_internal/cpython-3.11.12/lib/python3.11/site-packages/_rocm_sdk_devel/lib/libhipsolver.so.1.0  /opt/_internal/cpython-3.11.12/lib/python3.11/site-packages/_rocm_sdk_devel/lib/librocblas.so.5.3  /opt/python/cp311-cp311/lib/python3.11/site-packages/_rocm_sdk_devel/lib/libamdhip64.so.7.3.53390-a160f7a7d7  /opt/python/cp311-cp311/lib/python3.11/site-packages/_rocm_sdk_devel/lib/libhipblaslt.so.1.2  lib/libgtest.a  -pthread && /opt/_internal/cpython-3.11.12/lib/python3.11/site-packages/cmake/data/bin/cmake -E __run_co_compile --lwyu="ldd;-u;-r" --source=bin/NamedTensor_test && :
> > /opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: /opt/_internal/cpython-3.11.12/lib/python3.11/site-packages/_rocm_sdk_devel/lib/librccl.so.1: undefined reference to `ncclSymkGetKernelPtr(ncclSymkKernelId, int, ncclDataType_t)'
> > collect2: error: ld returned 1 exit status
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (that looks like #3268, which was resolved... you might have chosen a commit in the broken range)
> 
> Yes, I see same rccl linking error (`undefined reference to ncclSymkGetKernelPtr(ncclSymkKernelId, int, ncclDataType_t)'`) with all the pytorch build which is triggered yesterday with this PR. I see revert for this failure is already merged in main branch (#3271). Now, I've rebased this PR with latest main branch which includes above revert and restarted the full build. https://github.com/ROCm/TheRock/actions/runs/21898608999 https://github.com/ROCm/TheRock/actions/runs/21898615949

Both Linux & Windows full build completed successfully.
Pytorch builds completed successfully except following known issues.
- All targets - Pytorch build with release/2.10 branch + py3.12/py3.13 fails with "ModuleNotFoundError: No module named 'pkg_resources'" - https://github.com/ROCm/TheRock/actions/runs/21900504708/job/63227227850
- gfx1151 - Pytorch build fails with "error: use of undeclared identifier 'CK_BUFFER_RESOURCE_3RD_DWORD'" - https://github.com/ROCm/TheRock/actions/runs/21896579618/job/63213994080

**Comment by amd-justchen** [comment]
For visibility, cross posting context about approving with known infra failures from chats:
> - Linux's Test rocm[libraries] wheels | gfx1151 - Seems to be infra issue with container initialization failure
> - Windows' Test hip-test (shard 3/4) (gfx1151) - Infra issue from inability to setup environment due to previously running test process
> - Windows' Test hip-test (shard 4/4) (gfx1151) - same as above
> - Windows' Test miopen (shard 3/4) (gfx1151) - test crash throwing exceptions for MIopen which I believe are known failures due to too heavy tests running on light hardware (this test machine has only 16G of RAM, 12G dedicated for system 4G for VRAM) and are currently undergoing filtering. Other Shards were able to complete.

tracking issue for `process in use` failures: https://github.com/ROCm/TheRock/issues/2784
