### ISSUE TITLE
hipBLASLt unexpected keyword argument from Python during configure

### ISSUE THREAD

**Issue by ScottTodd** [ROCm/TheRock#158]
I'm seeing these error logs: https://gist.github.com/ScottTodd/696d060c2799bf2fdbbf623a72fcebe1 when I try to configure + build on Ubuntu 22.04.

Error log snippets:
```
[build] [hipBLASLt configure] Error Code: '/home/nod/dev/projects/TheRock/build/math-libs/BLAS/hipBLASLt/build/virtualenv/bin/python3.13' '-m' 'pip' 'install' '/home/nod/dev/projects/TheRock/math-libs/BLAS/hipBLASLt/tensilelite'
[build] [hipBLASLt configure] 
[build] [hipBLASLt configure] StdOut: Processing /home/nod/dev/projects/TheRock/math-libs/BLAS/hipBLASLt/tensilelite
[build] [hipBLASLt configure]   Preparing metadata (setup.py): started
[build] [hipBLASLt configure]   Preparing metadata (setup.py): finished with status 'error'

[build] [hipBLASLt configure]           File "/home/nod/dev/projects/TheRock/build/math-libs/BLAS/hipBLASLt/build/virtualenv/lib/python3.13/site-packages/setuptools/_core_metadata.py", line 290, in _distribution_fullname
[build] [hipBLASLt configure]             canonicalize_version(version, strip_trailing_zero=False),
[build] [hipBLASLt configure]             ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[build] [hipBLASLt configure]         TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
[build] [hipBLASLt configure]         [end of output]
```

That points to https://github.com/pypa/setuptools/issues/4483. So some package is using a version that doesn't support that keyword argument... but why is the venv using python3.13 when I told CMake to use my 3.12 venv?

Repro steps:

```bash
git clone git@github.com:ROCm/TheRock.git
pip install meson  # outside of venv
python3.12 -m venv .venv
source .venv/bin/activate
python ./build_tools/fetch_sources.py
pip install CppHeaderParser==2.7.4 meson==1.7.0 tomli==2.2.1
sudo apt install gfortran git-lfs ninja-build cmake g++ pkg-config xxd libgtest-dev
sudo apt install patchelf

cmake \
  -G Ninja \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE \
  -DCMAKE_C_COMPILER=/usr/bin/clang-18 \
  -DCMAKE_CXX_COMPILER=/usr/bin/clang++-18 \
  -DPython3_EXECUTABLE=/home/nod/dev/projects/TheRock/.venv/bin/python \
  -DPython_EXECUTABLE=/home/nod/dev/projects/TheRock/.venv/bin/python \
  -DCMAKE_C_COMPILER_LAUNCHER=ccache \
  -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
  -DTHEROCK_AMDGPU_FAMILIES=gfx110X\
  -S/home/nod/dev/projects/TheRock \
  -B/home/nod/dev/projects/TheRock/build

cmake --build /home/nod/dev/projects/TheRock/build --config Release --target all --
```

**Comment by ScottTodd** [comment]
Found the CMake that is running: https://github.com/ROCm/hipBLASLt/blob/mainline/cmake/virtualenv.cmake

This part of the logs shows the system Python 3.13 getting used and incompatible packages being installed:

```
[build] [hipBLASLt configure] -- Resolving system find_package(Python) (not found in super-project ZLIB;zstd;AMDDeviceLibs;Clang;LLD;LLVM;amd_comgr;rocm-core;rocprofiler-register;BZip2;LibElf;libdw;NUMA;hsakmt;hsa-runtime64;hip;HIP;hip-lang;hiprtc;hipblas-common;msgpack-cxx)
[build] [hipBLASLt configure] -- Found Python: /usr/bin/python3.13 (found version "3.13.2") found components: Interpreter
[build] [hipBLASLt configure] '/usr/bin/python3.13' '-m' 'venv' '/home/nod/dev/projects/TheRock/build/math-libs/BLAS/hipBLASLt/build/virtualenv' '--system-site-packages' '--clear'
[build] [hipBLASLt configure] '/home/nod/dev/projects/TheRock/build/math-libs/BLAS/hipBLASLt/build/virtualenv/bin/python3.13' '-m' 'pip' 'install' '--upgrade' 'pip'
[build] [hipBLASLt configure] Requirement already satisfied: pip in ./virtualenv/lib/python3.13/site-packages (24.3.1)
[build] [hipBLASLt configure] Collecting pip
[build] [hipBLASLt configure]   Using cached pip-25.0.1-py3-none-any.whl.metadata (3.7 kB)
[build] [hipBLASLt configure] Using cached pip-25.0.1-py3-none-any.whl (1.8 MB)
[build] [hipBLASLt configure] Installing collected packages: pip
[build] [hipBLASLt configure]   Attempting uninstall: pip
[build] [hipBLASLt configure]     Found existing installation: pip 24.3.1
[build] [hipBLASLt configure]     Uninstalling pip-24.3.1:
[build] [hipBLASLt configure]       Successfully uninstalled pip-24.3.1
[build] [hipBLASLt configure] Successfully installed pip-25.0.1
[build] [hipBLASLt configure] '/home/nod/dev/projects/TheRock/build/math-libs/BLAS/hipBLASLt/build/virtualenv/bin/python3.13' '-m' 'pip' 'install' '--upgrade' 'setuptools'
[build] [hipBLASLt configure] Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (59.6.0)
[build] [hipBLASLt configure] Collecting setuptools
[build] [hipBLASLt configure]   Using cached setuptools-75.8.2-py3-none-any.whl.metadata (6.7 kB)
[build] [hipBLASLt configure] Using cached setuptools-75.8.2-py3-none-any.whl (1.2 MB)
[build] [hipBLASLt configure] Installing collected packages: setuptools
[build] [hipBLASLt configure]   Attempting uninstall: setuptools
[build] [hipBLASLt configure]     Found existing installation: setuptools 59.6.0
[build] [hipBLASLt configure]     Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /home/nod/dev/projects/TheRock/build/math-libs/BLAS/hipBLASLt/build/virtualenv
[build] [hipBLASLt configure]     Can't uninstall 'setuptools'. No files were found to uninstall.
[build] [hipBLASLt configure] Successfully installed setuptools-75.8.2
```

**Comment by ScottTodd** [comment]
I think this fixes it:
```cmake
    execute_process(
      COMMAND ${VIRTUALENV_BIN_DIR}/${VIRTUALENV_PYTHON_EXENAME} -m pip install --upgrade packaging
      COMMAND_ECHO STDOUT
    )
```

Running a build then will push a patch and PR.

**Comment by ScottTodd** [comment]
🤦 same issue in rocBLAS

**Comment by ScottTodd** [comment]
Huh. My Python 3.13 is sorta broken:

```
$ python3.13 -m pip freeze
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3/dist-packages/pip/__main__.py", line 29, in <module>
    from pip._internal.cli.main import main as _main
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/usr/lib/python3/dist-packages/pip/_internal/configuration.py", line 26, in <module>
    from pip._internal.utils.logging import getLogger
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/logging.py", line 27, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/misc.py", line 39, in <module>
    from pip._internal.locations import get_major_minor_version
  File "/usr/lib/python3/dist-packages/pip/_internal/locations/__init__.py", line 14, in <module>
    from . import _distutils, _sysconfig
  File "/usr/lib/python3/dist-packages/pip/_internal/locations/_distutils.py", line 9, in <module>
    from distutils.cmd import Command as DistutilsCommand
ModuleNotFoundError: No module named 'distutils'
```

These projects should still be more robust and declare or install what they need to function though.
