### ISSUE TITLE
[Issue] Linux PyTorch gfx950-dcgpu: 8 test failures on torch nightly (2.13)

### ISSUE THREAD

**Issue by amd-chiranjeevi** [ROCm/TheRock#5596]
## Context
- Workflow: Release portable Linux PyTorch Wheels
- Workflow file: `.github/workflows/release_portable_linux_pytorch_wheels.yml`
- Failing run: [↗ View run](https://github.com/ROCm/TheRock/actions/runs/26809392716)
- Platform: `Linux`
- Impacted Arch: `gfx950-dcgpu`
- PyTorch Version: `nightly` (`2.13.0a0+rocm7.14.0a20260602`)
- Python Version: `3.13, 3.11, 3.10, 3.14`

## Failed Tests (8)
```
test_nn.py::TestNNDeviceTypeCUDA::test_CTCLoss_cudnn_cuda
test_nn.py::TestNNDeviceTypeCUDA::test_LSTM_dropout_per_call_randomness_dropout_p_0_5_training_True_cuda
test_nn.py::TestNNDeviceTypeCUDA::test_ctc_loss_cudnn_tensor_cuda_cuda
test_nn.py::TestNNDeviceTypeCUDA::test_upsamplingNearest2d_launch_rocm_cuda
test_cuda.py::TestCuda::test_hip_device_count
test_cuda.py::TestCudaAllocator::test_memory_compile_regions
test_cuda.py::TestMemPool::test_mempool_empty_cache_inactive
test_cuda.py::TestMemPool::test_mempool_limited_memory_with_allocator
```

## Root Cause
The skip-list loader in `run_pytorch_tests.py` detects torch version `2.13` and tries to load `external-builds/pytorch/skip_tests/pytorch_2.13.py`. That file does not exist, so only `generic.py` is loaded. All the tests above are already marked as known failures in the stable-version skip files (`pytorch_2.9.py` – `pytorch_2.12.py`), but those exclusions do not apply to nightly.

The most structurally notable error (two test failures):
```
/__w/TheRock/TheRock/.venv/lib/python3.13/site-packages/torch/include/ATen/hip/Exceptions.h:5:10: fatal error: 'hipblas/hipblas.h' file not found
    5 | #include <hipblas/hipblas.h>
      |          ^~~~~~~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.
FAILED [7.2476s]  test_cuda.py::TestMemPool::test_mempool_limited_memory_with_allocator
```

## Suggested Fix 
Add `external-builds/pytorch/skip_tests/pytorch_2.13.py` mirroring the known-failing entries from `pytorch_2.12.py` for the tests listed above. The `test_upsamplingNearest2d_launch_rocm_cuda` failure on gfx950 is also separately tracked in #5270.

## Sample Failing Job
- https://github.com/ROCm/TheRock/actions/runs/26809392716/job/79046051654 (py 3.13, torch nightly)
- https://github.com/ROCm/TheRock/actions/runs/26809392716/job/79042308646 py3.11 nightly
- https://github.com/ROCm/TheRock/actions/runs/26809392716/job/79044526216 py3.10
- https://github.com/ROCm/TheRock/actions/runs/26809392716/job/79045243139 py3.14

**Comment by amd-chiranjeevi** [comment]
skipping the tests here https://github.com/ROCm/TheRock/pull/5600

**Comment by Melantha-S** [comment]
This issue has been migrated to Jira Cloud: https://amd-hub.atlassian.net/browse/AIPYTORCH-632
