### ISSUE TITLE
[Issue]: Linux - Build from source fails due to CMake version

### ISSUE THREAD

**Issue by Z3KSSS** [ROCm/TheRock#1916]
### Problem Description

Hey all,

Trying to build from source as per README but the amd-llvm portion of the build fails due to a CMake version mismatch. The error happens late in the first build and errors out on subsequent builds. Maybe a mismatch between upstream amd-llvm, fftw3f, and TheRock:

TheRock/CMakeList.txt:5:
`cmake_minimum_required(VERSION 3.25)  # Also update in alternative_os_setup.md`

TheRock/compiler/amd-llvm/offload/hostexec/CMakeLists.txt:13:
` cmake_minimum_required(VERSION 3.0 FATAL_ERROR)`

First error output comes as follows:
`
[amd-llvm] -- Building x86_64 plugin linked with libffi
[amd-llvm] -- Building the llvm-offload-device-info tool
[amd-llvm] -- Building the llvm-omp-kernel-replay tool
[amd-llvm] CMake Error at /home/k/Builds/TheRock/compiler/amd-llvm/offload/hostexec/CMakeLists.txt:13 (cmake_minimum_required):
[amd-llvm]   Compatibility with CMake < 3.5 has been removed from CMake.
[amd-llvm] 
[amd-llvm]   Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
[amd-llvm]   to tell CMake that the project requires at least <min> but has been updated
[amd-llvm]   to work with policies introduced by <max> or earlier.
[amd-llvm] 
[amd-llvm]   Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
[amd-llvm] 
[amd-llvm] 
[amd-llvm] -- Configuring incomplete, errors occurred!
[amd-llvm] FAILED: [code=1] runtimes/runtimes-stamps/runtimes-configure /home/k/Builds/TheRock/build/compiler/amd-llvm/build/runtimes/runtimes-stamps/runtimes-configure
`

And throws 2 more errors:
`
[1/121] Configure sub-project therock-fftw3 (in background)
FAILED: [code=1] third-party/fftw3/build_fftw3/stamp/configure.stamp third-party/fftw3/build_fftw3/build/CMakeCache.txt third-party/fftw3/build_fftw3/build/cmake_install.cmake compile_commands_fragment_therock-fftw3.json /home/k/Builds/TheRock/build/third-party/fftw3/build_fftw3/stamp/configure.stamp /home/k/Builds/TheRock/build/third-party/fftw3/build_fftw3/build/CMakeCache.txt /home/k/Builds/TheRock/build/third-party/fftw3/build_fftw3/build/cmake_install.cmake /home/k/Builds/TheRock/build/compile_commands_fragment_therock-fftw3.json 
cd /home/k/Builds/TheRock/build/third-party/fftw3/build_fftw3/build && /home/k/Builds/TheRock/.venv/bin/python3.13 /home/k/Builds/TheRock/build_tools/teatime.py --log-timestamps --label therock-fftw3\ configure --no-interactive /home/k/Builds/TheRock/build/logs/therock-fftw3_configure.log -- /usr/bin/cmake -E env --unset=ROCM_PATH --unset=ROCM_DIR --unset=HIP_PATH --unset=HIP_DIR -- /usr/bin/cmake -GNinja -B/home/k/Builds/TheRock/build/third-party/fftw3/build_fftw3/build -S/home/k/Builds/TheRock/build/third-party/fftw3/source -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/k/Builds/TheRock/build/third-party/fftw3/build_fftw3/stage -DTHEROCK_STAGE_INSTALL_ROOT=/home/k/Builds/TheRock/build/third-party/fftw3/build_fftw3/stage -DCMAKE_TOOLCHAIN_FILE=/home/k/Builds/TheRock/build/third-party/fftw3/build_fftw3/_toolchain.cmake -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=/home/k/Builds/TheRock/build/third-party/fftw3/build_fftw3/_init.cmake -DBUILD_SHARED_LIBS=ON -DENABLE_THREADS=ON && /usr/bin/cmake -E touch /home/k/Builds/TheRock/build/third-party/fftw3/build_fftw3/build/compile_commands.json && /usr/bin/cmake -E touch /home/k/Builds/TheRock/build/third-party/fftw3/build_fftw3/stamp/configure.stamp && /usr/bin/cmake -E copy /home/k/Builds/TheRock/build/third-party/fftw3/build_fftw3/build/compile_commands.json /home/k/Builds/TheRock/build/compile_commands_fragment_therock-fftw3.json
[therock-fftw3 configure] CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
[therock-fftw3 configure]   Compatibility with CMake < 3.5 has been removed from CMake.
[therock-fftw3 configure] 
[therock-fftw3 configure]   Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
[therock-fftw3 configure]   to tell CMake that the project requires at least <min> but has been updated
[therock-fftw3 configure]   to work with policies introduced by <max> or earlier.
[therock-fftw3 configure] 
[therock-fftw3 configure]   Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
[therock-fftw3 configure] 
[therock-fftw3 configure] 
[therock-fftw3 configure] -- Configuring incomplete, errors occurred!
[2/121] Configure sub-project therock-fftw3f (in background)
FAILED: [code=1] third-party/fftw3/build_fftw3f/stamp/configure.stamp third-party/fftw3/build_fftw3f/build/CMakeCache.txt third-party/fftw3/build_fftw3f/build/cmake_install.cmake compile_commands_fragment_therock-fftw3f.json /home/k/Builds/TheRock/build/third-party/fftw3/build_fftw3f/stamp/configure.stamp /home/k/Builds/TheRock/build/third-party/fftw3/build_fftw3f/build/CMakeCache.txt /home/k/Builds/TheRock/build/third-party/fftw3/build_fftw3f/build/cmake_install.cmake /home/k/Builds/TheRock/build/compile_commands_fragment_therock-fftw3f.json 
cd /home/k/Builds/TheRock/build/third-party/fftw3/build_fftw3f/build && /home/k/Builds/TheRock/.venv/bin/python3.13 /home/k/Builds/TheRock/build_tools/teatime.py --log-timestamps --label therock-fftw3f\ configure --no-interactive /home/k/Builds/TheRock/build/logs/therock-fftw3f_configure.log -- /usr/bin/cmake -E env --unset=ROCM_PATH --unset=ROCM_DIR --unset=HIP_PATH --unset=HIP_DIR -- /usr/bin/cmake -GNinja -B/home/k/Builds/TheRock/build/third-party/fftw3/build_fftw3f/build -S/home/k/Builds/TheRock/build/third-party/fftw3/source -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/k/Builds/TheRock/build/third-party/fftw3/build_fftw3f/stage -DTHEROCK_STAGE_INSTALL_ROOT=/home/k/Builds/TheRock/build/third-party/fftw3/build_fftw3f/stage -DCMAKE_TOOLCHAIN_FILE=/home/k/Builds/TheRock/build/third-party/fftw3/build_fftw3f/_toolchain.cmake -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=/home/k/Builds/TheRock/build/third-party/fftw3/build_fftw3f/_init.cmake -DENABLE_FLOAT=ON -DBUILD_SHARED_LIBS=ON -DENABLE_THREADS=ON && /usr/bin/cmake -E touch /home/k/Builds/TheRock/build/third-party/fftw3/build_fftw3f/build/compile_commands.json && /usr/bin/cmake -E touch /home/k/Builds/TheRock/build/third-party/fftw3/build_fftw3f/stamp/configure.stamp && /usr/bin/cmake -E copy /home/k/Builds/TheRock/build/third-party/fftw3/build_fftw3f/build/compile_commands.json /home/k/Builds/TheRock/build/compile_commands_fragment_therock-fftw3f.json
[therock-fftw3f configure] CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
[therock-fftw3f configure]   Compatibility with CMake < 3.5 has been removed from CMake.
[therock-fftw3f configure] 
[therock-fftw3f configure]   Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
[therock-fftw3f configure]   to tell CMake that the project requires at least <min> but has been updated
[therock-fftw3f configure]   to work with policies introduced by <max> or earlier.
[therock-fftw3f configure] 
[therock-fftw3f configure]   Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
[therock-fftw3f configure] 
[therock-fftw3f configure] 
[therock-fftw3f configure] -- Configuring incomplete, errors occurred!
FAILED: [code=1] compiler/amd-llvm/stamp/build.stamp /home/k/Builds/TheRock/build/compiler/amd-llvm/stamp/build.stamp 
cd /home/k/Builds/TheRock/build/compiler/amd-llvm/build && /home/k/Builds/TheRock/.venv/bin/python3.13 /home/k/Builds/TheRock/build_tools/teatime.py --log-timestamps --label amd-llvm --interactive /home/k/Builds/TheRock/build/logs/amd-llvm_build.log -- /usr/bin/cmake -E env --unset=ROCM_PATH --unset=ROCM_DIR --unset=HIP_PATH --unset=HIP_DIR -- /usr/bin/cmake --build /home/k/Builds/TheRock/build/compiler/amd-llvm/build && /usr/bin/cmake -E touch /home/k/Builds/TheRock/build/compiler/amd-llvm/stamp/build.stamp
ninja: build stopped: subcommand failed.
`

I did try the Common Issues\CMake commands in environment_setup_guide.md which was no help.

Cmake versions I've tried:
3.25
3.25.2
3.26
3.26.1
3.27
3.31.6
4.1.2

Additional linux info:
OS:
NAME="Arch Linux"
CPU: 
model name	: AMD RYZEN AI MAX+ 395 w/ Radeon 8060S
GPU:
  Name:                    AMD RYZEN AI MAX+ 395 w/ Radeon 8060S
  Marketing Name:          AMD RYZEN AI MAX+ 395 w/ Radeon 8060S
  Name:                    gfx1151                            
  Marketing Name:          Radeon 8060S Graphics              
      Name:                    amdgcn-amd-amdhsa--gfx1151         
      Name:                    amdgcn-amd-amdhsa--gfx11-generic   
  Name:                    aie2                               
  Marketing Name:          AIE-ML  

As well I'm running kernel 6.17.4-ba04.fc43.x86_64 from bazzite.

If I made any mistakes or if any other info is needed please let me know and I'll do my best to provide. Thank you all for the hardwork, it's truly appreciated!

### Operating System

Arch Linux

### CPU

AMD RYZEN AI MAX+ 395

### GPU

Radeon 8060S

### ROCm Version

Latest

### ROCm Component

rocm-cmake

### Steps to Reproduce

python3 -m venv .venv && source .venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt
python3 ./build_tools/fetch_sources.py
cmake -B build -GNinja . -DTHEROCK_AMDGPU_TARGETS=gfx1151
cmake --build build
*errors out*
pip install 'cmake<4'
hash -r
cmake --build build
*errors out*

### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support

/opt/rocm/bin/rocminfo --support
ROCk module is loaded
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.15
Runtime Ext Version:     1.7
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             
Mwaitx:                  DISABLED
XNACK enabled:           NO
DMAbuf Support:          YES
VMM Support:             YES

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    AMD RYZEN AI MAX+ 395 w/ Radeon 8060S
  Uuid:                    CPU-XX                             
  Marketing Name:          AMD RYZEN AI MAX+ 395 w/ Radeon 8060S
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      49152(0xc000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   5187                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            32                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Memory Properties:       
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    127390020(0x797d144) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    127390020(0x797d144) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    127390020(0x797d144) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 4                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    127390020(0x797d144) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 2                  
*******                  
  Name:                    gfx1151                            
  Uuid:                    GPU-XX                             
  Marketing Name:          Radeon 8060S Graphics              
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      32(0x20) KB                        
    L2:                      2048(0x800) KB                     
    L3:                      32768(0x8000) KB                   
  Chip ID:                 5510(0x1586)                       
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          128(0x80)                          
  Max Clock Freq. (MHz):   2900                               
  BDFID:                   50176                              
  Internal Node ID:        1                                  
  Compute Unit:            40                                 
  SIMDs per CU:            2                                  
  Shader Engines:          2                                  
  Shader Arrs. per Eng.:   2                                  
  WatchPts on Addr. Ranges:4                                  
  Coherent Host Access:    FALSE                              
  Memory Properties:       APU
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          32(0x20)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        32(0x20)                           
  Max Work-item Per CU:    1024(0x400)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Packet Processor uCode:: 32                                 
  SDMA engine uCode::      17                                 
  IOMMU Support::          None                               
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    63695008(0x3cbe8a0) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: EXTENDED FINE GRAINED
      Size:                    63695008(0x3cbe8a0) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:2048KB                             
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 3                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Recommended Granule:0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx1151         
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
    ISA 2                    
      Name:                    amdgcn-amd-amdhsa--gfx11-generic   
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*******                  
Agent 3                  
*******                  
  Name:                    aie2                               
  Uuid:                    AIE-XX                             
  Marketing Name:          AIE-ML                             
  Vendor Name:             AMD                                
  Feature:                 AGENT_DISPATCH                     
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        1(0x1)                             
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          64(0x40)                           
  Queue Type:              SINGLE                             
  Node:                    0                                  
  Device Type:             DSP                                
  Cache Info:              
    L2:                      2048(0x800) KB                     
    L3:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          0(0x0)                             
  Max Clock Freq. (MHz):   0                                  
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            0                                  
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:0                                  
  Memory Properties:       
  Features:                AGENT_DISPATCH
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: KERNARG, COARSE GRAINED
      Size:                    127390020(0x797d144) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    65536(0x10000) KB                  
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:0KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    127390020(0x797d144) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Recommended Granule:4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*** Done ***

**Comment by tcgu-amd** [comment]
Hi @Z3KSSS, thanks for reaching out! What you are experiencing does seem pretty odd. I wasn't able to reproduce it on Ubuntu. That being said, have you tried adding -DCMAKE_POLICY_VERSION_MINIMUM=3.25 as the error log suggested?

**Comment by Z3KSSS** [comment]
Hey @tcgu-amd, thanks for the response.

I just tried to build with CMake 3.31.6:
$cmake -B build -GNinja . -DTHEROCK_AMDGPU_TARGETS=gfx1151 -DCMAKE_POLICY_VERSION_MINIMUM=3.5
$cmake --build build

The build doesn't seem go as far as without  -DCMAKE_POLICY_VERSION_MINIMUM=3.5 before I get errors. As well I'm seeing different errors, first attempt:

`[amdsmi] 
[amdsmi SUCCEEDED in 21 seconds]
[249/363] Populate artifact host-suite-sparse
FAILED: [code=1] compiler/amd-llvm/stamp/build.stamp /home/k/Builds/TheRock/build/compiler/amd-llvm/stamp/build.stamp 
cd /home/k/Builds/TheRock/build/compiler/amd-llvm/build && /home/k/Builds/TheRock/.venv/bin/python3.13 /home/k/Builds/TheRock/build_tools/teatime.py --log-timestamps --label amd-llvm --interactive /home/k/Builds/TheRock/build/logs/amd-llvm_build.log -- /home/k/Builds/TheRock/.venv/lib/python3.13/site-packages/cmake/data/bin/cmake -E env --unset=ROCM_PATH --unset=ROCM_DIR --unset=HIP_PATH --unset=HIP_DIR -- /home/k/Builds/TheRock/.venv/lib/python3.13/site-packages/cmake/data/bin/cmake --build /home/k/Builds/TheRock/build/compiler/amd-llvm/build && /home/k/Builds/TheRock/.venv/lib/python3.13/site-packages/cmake/data/bin/cmake -E touch /home/k/Builds/TheRock/build/compiler/amd-llvm/stamp/build.stamp
ninja: build stopped: subcommand failed.`

And subsequent attempts:

`[amd-llvm] /home/k/Builds/TheRock/compiler/amd-llvm/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cpp:489:31: error: invalid application of 'sizeof' to an incomplete type 'struct termio'
[amd-llvm]   489 |   unsigned struct_termio_sz = sizeof(struct termio);
[amd-llvm]       |                               ^     ~~~~~~~~~~~~~~~
[amd-llvm] /home/k/Builds/TheRock/compiler/amd-llvm/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cpp:489:45: note: forward declaration of '__sanitizer::termio'
[amd-llvm]   489 |   unsigned struct_termio_sz = sizeof(struct termio);
[amd-llvm]       |                                             ^
[amd-llvm] 1 error generated.
[amd-llvm] [57/1533] Building CXX object compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.x86_64.dir/sanitizer_platform_limits_posix.cpp.o
[amd-llvm] FAILED: [code=1] compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.x86_64.dir/sanitizer_platform_limits_posix.cpp.o 
[amd-llvm] /home/k/Builds/TheRock/build/compiler/amd-llvm/build/bin/clang++ --target=x86_64-unknown-linux-gnu -DHAVE_RPC_XDR_H=0 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/home/k/Builds/TheRock/rocm-systems/projects/rocr-runtime/runtime/hsa-runtime/inc -I/home/k/Builds/TheRock/compiler/amd-llvm/amd/comgr/include -I/home/k/Builds/TheRock/compiler/amd-llvm/compiler-rt/lib/sanitizer_common/.. -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -Wall -Wno-unused-parameter -O3 -DNDEBUG -std=c++17 -m64 -fPIC -fno-builtin -fno-exceptions -fomit-frame-pointer -funwind-tables -fno-stack-protector -fno-sanitize=safe-stack -fvisibility=hidden -fno-lto -Wthread-safety -Wthread-safety-reference -Wthread-safety-beta -O3 -gline-tables-only -DSANITIZER_AMDGPU=1 -Wno-gnu -Wno-variadic-macros -Wno-c99-extensions -ftrivial-auto-var-init=pattern -nostdinc++ -Wno-format -fno-rtti -Wframe-larger-than=570 -Wglobal-constructors -MD -MT compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.x86_64.dir/sanitizer_platform_limits_posix.cpp.o -MF compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.x86_64.dir/sanitizer_platform_limits_posix.cpp.o.d -o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.x86_64.dir/sanitizer_platform_limits_posix.cpp.o -c /home/k/Builds/TheRock/compiler/amd-llvm/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cpp
[amd-llvm] /home/k/Builds/TheRock/compiler/amd-llvm/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cpp:489:31: error: invalid application of 'sizeof' to an incomplete type 'struct termio'
[amd-llvm]   489 |   unsigned struct_termio_sz = sizeof(struct termio);
[amd-llvm]       |                               ^     ~~~~~~~~~~~~~~~
[amd-llvm] /home/k/Builds/TheRock/compiler/amd-llvm/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cpp:489:45: note: forward declaration of '__sanitizer::termio'
[amd-llvm]   489 |   unsigned struct_termio_sz = sizeof(struct termio);
[amd-llvm]       |                                             ^
[amd-llvm] 1 error generated.
[amd-llvm] [58/1533] Building CXX object compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonCoverage.i386.dir/sanitizer_coverage_win_sections.cpp.o`

`[amd-llvm] [87/1533] Building CXX object offload/hostexec/CMakeFiles/amdgpu_hostexec_services.dir/services/amdgpu_hostexec.cpp.o
[amd-llvm] [88/1533] Building LLVM bitcode Xteams.cpp-amdgpu.bc
[amd-llvm] [89/1533] Building LLVM bitcode Xteams.cpp-nvptx.bc
[amd-llvm] ninja: build stopped: subcommand failed.
[amd-llvm] FAILED: [code=1] runtimes/runtimes-stamps/runtimes-build /home/k/Builds/TheRock/build/compiler/amd-llvm/build/runtimes/runtimes-stamps/runtimes-build 
[amd-llvm] cd /home/k/Builds/TheRock/build/compiler/amd-llvm/build/runtimes/runtimes-bins && /home/k/Builds/TheRock/.venv/lib/python3.13/site-packages/cmake/data/bin/cmake --build .
[amd-llvm] ninja: build stopped: subcommand failed.
[amd-llvm FAILED WITH CODE 1 in 2 seconds]
FAILED: [code=1] compiler/amd-llvm/stamp/build.stamp /home/k/Builds/TheRock/build/compiler/amd-llvm/stamp/build.stamp 
cd /home/k/Builds/TheRock/build/compiler/amd-llvm/build && /home/k/Builds/TheRock/.venv/bin/python3.13 /home/k/Builds/TheRock/build_tools/teatime.py --log-timestamps --label amd-llvm --interactive /home/k/Builds/TheRock/build/logs/amd-llvm_build.log -- /home/k/Builds/TheRock/.venv/lib/python3.13/site-packages/cmake/data/bin/cmake -E env --unset=ROCM_PATH --unset=ROCM_DIR --unset=HIP_PATH --unset=HIP_DIR -- /home/k/Builds/TheRock/.venv/lib/python3.13/site-packages/cmake/data/bin/cmake --build /home/k/Builds/TheRock/build/compiler/amd-llvm/build && /home/k/Builds/TheRock/.venv/lib/python3.13/site-packages/cmake/data/bin/cmake -E touch /home/k/Builds/TheRock/build/compiler/amd-llvm/stamp/build.stamp
ninja: build stopped: subcommand failed.`

Let me know if there's any more information I can provide that might help or if I should try with a different version of CMake.

**Comment by HereThereBeDragons** [comment]
can you please double check that the cmake you are using in your python env to build theRock is also the correct cmake version >= 3.25?

at one point i had the issue where i thought i had the correct cmake installed, just to learn that in the python env some other cmake was used.

**Comment by tcgu-amd** [comment]
Hi @Z3KSSS, since this issue can't be reproduced, and there has not been further updates, I will be closing this for now. Please feel free to comment below if you require further support. Thanks!
