### ISSUE TITLE
[Feature] Fill in build/test matrix for more PyTorch versions

### ISSUE THREAD

**Issue by ScottTodd** [ROCm/TheRock#1677]
Our current build/test/release support matrix for PyTorch covers 2.7 for Linux and "main"/"nightly" for both Linux and Windows: https://github.com/ROCm/TheRock/tree/main/external-builds/pytorch#supported-pytorch-versions . We should generalize this to [latest, N, N -1] where N is the current (or soon to be upcoming) stable release version. Concretely we should add 2.8 and 2.9 now.

* Linux matrix is defined here: https://github.com/ROCm/TheRock/blob/472254848e7a6499547c39ae11294b1ddb7ee7d2/.github/workflows/release_portable_linux_pytorch_wheels.yml#L82-L92

* Windows does not have multiple versions in the matrix yet: https://github.com/ROCm/TheRock/blob/472254848e7a6499547c39ae11294b1ddb7ee7d2/.github/workflows/release_windows_pytorch_wheels.yml#L82-L86

We may need to land commits/patches onto our release branches at https://github.com/ROCm/pytorch for build or test failures. We should _not_ plan on backporting _features_ to release branches (for example, aotriton support for Windows landed after the 2.9 branch cut).

TBD how much of the matrix we should run nightly or eventually on every commit. These build and test jobs take a considerable time to run across Python 3.11, 3.12, and 3.13 and we don't yet have a cache configured for the builds. We'll also want to add Python 3.14 soon. We could decide to run just "latest" and/or "latest stable" on individual commits (or nightly jobs) and then run older release builds on TheRock's release branches (perhaps in a fork).

**Comment by ScottTodd** [comment]
I triggered some test runs from my https://github.com/ROCm/TheRock/tree/users/scotttodd/torch-matrix branch that fills in the matrix:

* Windows: https://github.com/ROCm/TheRock/actions/runs/18208387317
* Linux: https://github.com/ROCm/TheRock/actions/runs/18208394991

Hoping to see at least the checkout steps work as expected and succeed. Not sure what to expect for builds and tests.

**Comment by ScottTodd** [comment]
Workflow run results:

Workflow details | Logs | Status summary
-- | -- | --
Linux torch 2.7 | [logs here](https://github.com/ROCm/TheRock/actions/runs/18208394991/job/51902013478) | ✅ Build passed
Linux torch 2.8 | [logs here](https://github.com/ROCm/TheRock/actions/runs/18208394991/job/51902013497) | ✅ Build passed
Linux torch 2.9 | [logs here](https://github.com/ROCm/TheRock/actions/runs/18208394991/job/51902013519) | ❌ Checkout failed, missing `related_commits` file on release branch
Windows torch 2.8 | [logs here](https://github.com/ROCm/TheRock/actions/runs/18227101779/job/51901069767) | ❌ Checkout failed, couldn't find `related_commits`<br>(None for Windows? Maybe use `ubuntu` or `centos`, we use `centos` on Linux right now)
Windows torch 2.9 | [logs here](https://github.com/ROCm/TheRock/actions/runs/18227101779/job/51901069758) | ❌ Checkout failed, missing `related_commits` file on release branch

---

@jithunnair-amd what's the status of the https://github.com/ROCm/pytorch/tree/release/2.9 branch? When will it be ready?

I see that it does not yet have a `releated_commits` file like release/2.8 has:
* https://github.com/ROCm/pytorch/blob/release/2.8/related_commits
* https://github.com/ROCm/pytorch/blob/release/2.9/related_commits (404)

https://github.com/ROCm/TheRock/actions/runs/18208394991/job/51843871745#step:8:3667
```
Run ./external-builds/pytorch/pytorch_torch_repo.py checkout --gitrepo-origin https://github.com/ROCm/pytorch.git --repo-hashtag release/2.9 --patchset rocm_2.9
  ./external-builds/pytorch/pytorch_torch_repo.py checkout --gitrepo-origin https://github.com/ROCm/pytorch.git --repo-hashtag release/2.9 --patchset rocm_2.9
  ./external-builds/pytorch/pytorch_audio_repo.py checkout --require-related-commit
  ./external-builds/pytorch/pytorch_vision_repo.py checkout --require-related-commit
  ./external-builds/pytorch/pytorch_triton_repo.py checkout

...

 Traceback (most recent call last):
  File "/__w/TheRock/TheRock/./external-builds/pytorch/pytorch_audio_repo.py", line 141, in <module>
    main(sys.argv[1:])
  File "/__w/TheRock/TheRock/./external-builds/pytorch/pytorch_audio_repo.py", line 136, in main
    raise ValueError("Could not find torchaudio in pytorch/related_commits")
ValueError: Could not find torchaudio in pytorch/related_commits
```

**Comment by ScottTodd** [comment]
> ❌ Checkout failed, couldn't find `related_commits`
> (None for Windows? Maybe use `ubuntu` or `centos`, we use `centos` on Linux right now)

I think our code should be using centos on Windows also, but we have a bug where the pin file lookup assumes the directory path for the torch repo (and we use a non-default path on Windows to keep path lengths short). I'll fix that.

**Comment by jithunnair-amd** [comment]
> Workflow run results:
> 
> Workflow details	Logs	Status summary
> Linux torch 2.7	[logs here](https://github.com/ROCm/TheRock/actions/runs/18208394991/job/51902013478)	✅ Build passed
> Linux torch 2.8	[logs here](https://github.com/ROCm/TheRock/actions/runs/18208394991/job/51902013497)	✅ Build passed
> Linux torch 2.9	[logs here](https://github.com/ROCm/TheRock/actions/runs/18208394991/job/51902013519)	❌ Checkout failed, missing `related_commits` file on release branch
> Windows torch 2.8	[logs here](https://github.com/ROCm/TheRock/actions/runs/18227101779/job/51901069767)	❌ Checkout failed, couldn't find `related_commits`
> (None for Windows? Maybe use `ubuntu` or `centos`, we use `centos` on Linux right now)
> Windows torch 2.9	[logs here](https://github.com/ROCm/TheRock/actions/runs/18227101779/job/51901069758)	❌ Checkout failed, missing `related_commits` file on release branch
> [@jithunnair-amd](https://github.com/jithunnair-amd) what's the status of the https://github.com/ROCm/pytorch/tree/release/2.9 branch? When will it be ready?
> 
> I see that it does not yet have a `releated_commits` file like release/2.8 has:
> 
> * https://github.com/ROCm/pytorch/blob/release/2.8/related_commits
> * https://github.com/ROCm/pytorch/blob/release/2.9/related_commits (404)
> 
> https://github.com/ROCm/TheRock/actions/runs/18208394991/job/51843871745#step:8:3667
> 
> ```
> Run ./external-builds/pytorch/pytorch_torch_repo.py checkout --gitrepo-origin https://github.com/ROCm/pytorch.git --repo-hashtag release/2.9 --patchset rocm_2.9
>   ./external-builds/pytorch/pytorch_torch_repo.py checkout --gitrepo-origin https://github.com/ROCm/pytorch.git --repo-hashtag release/2.9 --patchset rocm_2.9
>   ./external-builds/pytorch/pytorch_audio_repo.py checkout --require-related-commit
>   ./external-builds/pytorch/pytorch_vision_repo.py checkout --require-related-commit
>   ./external-builds/pytorch/pytorch_triton_repo.py checkout
> 
> ...
> 
>  Traceback (most recent call last):
>   File "/__w/TheRock/TheRock/./external-builds/pytorch/pytorch_audio_repo.py", line 141, in <module>
>     main(sys.argv[1:])
>   File "/__w/TheRock/TheRock/./external-builds/pytorch/pytorch_audio_repo.py", line 136, in main
>     raise ValueError("Could not find torchaudio in pytorch/related_commits")
> ValueError: Could not find torchaudio in pytorch/related_commits
> ```

@ScottTodd We are actively working on getting the release/2.9 branch ready. It will be ready by this week with related_commits and other cherry-picks.

**Comment by ScottTodd** [comment]
Picking this back up, aiming to at least get Windows building from the 2.9 release branch

Some test workflow runs:

* Windows torch release/2.8: https://github.com/ROCm/TheRock/actions/runs/18513020558/job/52757784726
* Windows torch release/2.9: https://github.com/ROCm/TheRock/actions/runs/18512997354/job/52757715762

**Comment by ScottTodd** [comment]
Windows release/2.9 failed with
```
2025-10-15T00:23:25.0396508Z B:/src/torch/aten/src\ATen/native/transformers/hip/aotriton_adapter.h:7:10: fatal error: 'aotriton/dtypes.h' file not found
2025-10-15T00:23:25.0397147Z     7 | #include <aotriton/dtypes.h>
2025-10-15T00:23:25.0397427Z       |          ^~~~~~~~~~~~~~~~~~~
2025-10-15T00:23:25.0397714Z 1 error generated when compiling for host.
```

Proposed a cherry-pick onto the release branch to tentatively fix that: https://github.com/ROCm/pytorch/pull/2712

Windows release/2.8 failed with
```
2025-10-15T00:02:09.4746469Z FAILED: [code=1] third_party/fbgemm/CMakeFiles/fbgemm_generic.dir/src/FbgemmConv.cc.obj 
2025-10-15T00:02:09.4752402Z C:\home\runner\_work\_tool\Python\3.12.10\x64\Lib\site-packages\_rocm_sdk_devel\lib\llvm\bin\clang-cl.exe  /nologo -TP -DDISABLE_FBGEMM_AUTOVEC -IB:\src\torch\third_party\cpuinfo\include -IB:\src\torch\third_party\fbgemm\external\asmjit\src -IB:\src\torch\third_party\fbgemm\include -IB:\src\torch\third_party\fbgemm -imsvcB:\src\torch\third_party\protobuf\src -imsvcB:\src\torch\third_party\XNNPACK\include /DWIN32 /D_WINDOWS /EHsc /Zc:__cplusplus /bigobj /FS /utf-8 -DUSE_PTHREADPOOL -Xclang -fopenmp /wd4244 /wd4267 /wd4305 /wd4309 /O2 /Ob2 /DNDEBUG /bigobj -std:c++20 -MD -Z7 /showIncludes /Fothird_party\fbgemm\CMakeFiles\fbgemm_generic.dir\src\FbgemmConv.cc.obj /Fdthird_party\fbgemm\CMakeFiles\fbgemm_generic.dir\ -c -- B:\src\torch\third_party\fbgemm\src\FbgemmConv.cc
2025-10-15T00:02:09.4755618Z In file included from B:\src\torch\third_party\fbgemm\src\FbgemmConv.cc:15:
2025-10-15T00:02:09.4756436Z B:\src\torch\third_party\fbgemm\include\fbgemm/Fbgemm.h(127,16): error: no member named 'isA' in 'fbgemm::PackAWithRowOffset<unsigned char>'
2025-10-15T00:02:09.4757033Z   127 |     return PT::isA();
2025-10-15T00:02:09.4757267Z       |            ~~~~^
```

That would need one of the fbgemm submodule updates in pytorch's submodule cherry-picked, or a patch like https://github.com/ROCm/TheRock/blob/00404cc4a62a0953c0f9001d84d42081e76ea426/external-builds/pytorch/patches/pytorch/main/third_party/fbgemm/hipified/0001-Trim-constexpr-from-isA-to-improve-Windows-clang-cl-.patch (merged upstream as https://github.com/pytorch/FBGEMM/pull/4119)

**Comment by jithunnair-amd** [comment]
@ScottTodd We updated the release/2.9 branch with upstream release/2.9 changes as well as with cherry-picks from release/2.8.
