### PR TITLE
Bump rocm-systems submodules 20251024

### PR DESCRIPTION
**Pull request by lamikr**
1) dropped 0001-Patch-version-and-getpath-files-for-Windows.patch
 - applied to upstream with slight modifications
2) 0003-Use-is_versioned-true-consistently-in-both-Comgr-Loa.patch
- required modifications because patch
  a4bbd73dc6194cdc4aae0fc889b848a944b9bbea / Remove HSAIL support (#1183)
  had removed the if lightning check.
3. Added temporarily a patch to fix the build break caused by new code. Patch with fix suggestion send to upstream:
https://github.com/ROCm/rocm-systems/pull/1546

### CODE REVIEW

**Review by marbre — APPROVED** [review]
LGTM, thanks for the bump. Let's wait for the CI to see if all tests pass prior to merging.

**Comment by lamikr** [comment]
There is real build error here:

```
2025-10-24T20:50:59.1958561Z [hip-clr] /__w/TheRock/TheRock/rocm-systems/projects/clr/rocclr/os/os_posix.cpp:1013:71: error: cannot pass object of non-trivial type 'const std::string' (aka 'const basic_string<char>') through variadic function; call will abort at runtime [-Wnon-pod-varargs]
2025-10-24T20:50:59.1958769Z [hip-clr]  1013 |     ClPrint(amd::LOG_DEBUG, amd::LOG_RESOURCE, "%s cannot be opened", path);
2025-10-24T20:50:59.1958880Z [hip-clr]       |                                                                       ^
2025-10-24T20:50:59.1959604Z [hip-clr] /__w/TheRock/TheRock/rocm-systems/projects/clr/rocclr/os/os_posix.cpp:1013:71: error: cannot pass object of non-trivial type 'const std::string' (aka 'const basic_string<char>') through variadic function; call will abort at runtime [-Wnon-pod-varargs]
2025-10-24T20:50:59.1959683Z [hip-clr] 2 errors generated.


```

Fix would be:

```
diff --git a/projects/clr/rocclr/os/os_posix.cpp b/projects/clr/rocclr/os/os_posix.cpp
index a3766a71fd..2b807a628b 100644
--- a/projects/clr/rocclr/os/os_posix.cpp
+++ b/projects/clr/rocclr/os/os_posix.cpp
@@ -1010,7 +1010,7 @@ bool NumaNode::GetAffinity() {
   std::ifstream file(path);
   if (!file) {
     std::cerr << "Failed to open " << path << "\n";
-    ClPrint(amd::LOG_DEBUG, amd::LOG_RESOURCE, "%s cannot be opened", path);
+    ClPrint(amd::LOG_DEBUG, amd::LOG_RESOURCE, "%s cannot be opened", path.c_str());
     return false;
   }
   std::string line;
```

**Comment by lamikr** [comment]
Created PR to upstream: https://github.com/ROCm/rocm-systems/pull/1546

**Comment by lamikr** [comment]
Seeing more errors caused by commit:

```
commit a4bbd73dc6194cdc4aae0fc889b848a944b9bbea
    SWDEV-556684 - Remove HSAIL support (#1183)

```

Should we ask to revert it?

```
2025-10-25T00:10:27.1709408Z [hip-clr] ccache "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.44.35207\bin\Hostx64\x64\cl.exe"  /nologo /TP -DATI_OS_WIN -DCL_TARGET_OPENCL_VERSION=220 -DCL_USE_DEPRECATED_OPENCL_1_0_APIS -DCL_USE_DEPRECATED_OPENCL_1_1_APIS -DCL_USE_DEPRECATED_OPENCL_1_2_APIS -DCL_USE_DEPRECATED_OPENCL_2_0_APIS -DCOMGR_DYN_DLL -DGPUOPEN_CLIENT_INTERFACE_MAJOR_VERSION=42 -DHAVE_CL2_HPP -DHIP_MAJOR_VERSION=7 -DHIP_MINOR_VERSION=1 -DLITTLEENDIAN_CPU -DOPENCL_C_MAJOR=2 -DOPENCL_C_MINOR=0 -DOPENCL_MAJOR=2 -DOPENCL_MINOR=1 -DPAL_BUILD_RDF=1 -DPAL_CLIENT_INTERFACE_MAJOR_VERSION=932 -DPAL_DEVELOPER_BUILD=0 -DPAL_GPUOPEN_OCL -DPAL_KMT_BUILD=1 -DROCCLR_VERSION_GITHASH=\"017400b523\" -DWITH_PAL_DEVICE -IC:\home\runner\_work\TheRock\TheRock\rocm-systems\projects\clr\rocclr\.. -IC:\home\runner\_work\TheRock\TheRock\rocm-systems\projects\clr\rocclr -IC:\home\runner\_work\TheRock\TheRock\rocm-systems\projects\clr\rocclr\compiler\lib -IC:\home\runner\_work\TheRock\TheRock\rocm-systems\projects\clr\rocclr\compiler\lib\include -IC:\home\runner\_work\TheRock\TheRock\rocm-systems\projects\clr\rocclr\compiler\lib\backends\common -IC:\home\runner\_work\TheRock\TheRock\rocm-systems\projects\clr\rocclr\device -IC:\home\runner\_work\TheRock\TheRock\rocm-systems\projects\clr\rocclr\elf -IC:\home\runner\_work\TheRock\TheRock\rocm-systems\projects\clr\rocclr\include -IC:\home\runner\_work\TheRock\TheRock\rocm-systems\projects\clr\opencl\khronos\headers\opencl2.2\CL -IC:\home\runner\_work\TheRock\TheRock\rocm-systems\projects\clr\opencl\khronos\headers\opencl2.2\CL\.. -IC:\home\runner\_work\TheRock\TheRock\rocm-systems\projects\clr\opencl\khronos\headers\opencl2.2\CL\..\.. -IC:\home\runner\_work\TheRock\TheRock\rocm-systems\projects\clr\opencl\khronos\headers\opencl2.2\CL\..\..\.. -IC:\home\runner\_work\TheRock\TheRock\rocm-systems\projects\clr\opencl\khronos\headers\opencl2.2\CL\..\..\..\.. -IC:\home\runner\_work\TheRock\TheRock\rocm-systems\projects\clr\opencl\khronos\headers\opencl2.2\CL\..\..\..\..\amdocl -IC:\home\runner\_work\TheRock\TheRock\rocm-systems\shared\amdgpu-windows-interop\pal\inc -IC:\home\runner\_work\TheRock\TheRock\rocm-systems\shared\amdgpu-windows-interop\pal\inc\core -IC:\home\runner\_work\TheRock\TheRock\rocm-systems\shared\amdgpu-windows-interop\pal\inc\gpuUtil -IC:\home\runner\_work\TheRock\TheRock\rocm-systems\shared\amdgpu-windows-interop\pal\inc\util -IC:\home\runner\_work\TheRock\TheRock\rocm-systems\shared\amdgpu-windows-interop\pal\shared\inc -IC:\home\runner\_work\TheRock\TheRock\rocm-systems\shared\amdgpu-windows-interop\pal\shared\devdriver\shared\legacy\inc -IC:\home\runner\_work\TheRock\TheRock\rocm-systems\shared\amdgpu-windows-interop\pal\shared\devdriver\third_party\dd_crc32\inc -IC:\home\runner\_work\TheRock\TheRock\rocm-systems\shared\amdgpu-windows-interop\pal\shared\metrohash\src -IC:\home\runner\_work\TheRock\TheRock\rocm-systems\shared\amdgpu-windows-interop\sc\HSAIL\ext\loader -IC:\home\runner\_work\TheRock\TheRock\rocm-systems\shared\amdgpu-windows-interop\hsail-compiler\lib\loaders\elf\utils\libelf\..\..\..\..\..\lib\loaders\elf\utils\common -IC:\home\runner\_work\TheRock\TheRock\rocm-systems\shared\amdgpu-windows-interop\hsail-compiler\lib\loaders\elf\utils\libelf\..\..\..\..\..\lib\loaders\elf\utils\common\win32 -IC:\home\runner\_work\TheRock\TheRock\rocm-systems\shared\amdgpu-windows-interop\hsail-compiler\lib\loaders\elf\utils\libelf\..\..\..\..\..\lib\loaders\elf\utils\libelf -IC:\home\runner\_work\TheRock\TheRock\rocm-systems\shared\amdgpu-windows-interop\sc\HSAIL\ext\libamdhsacode -IC:\home\runner\_work\TheRock\TheRock\rocm-systems\shared\amdgpu-windows-interop\sc\HSAIL\ext\libamdhsacode\..\..\include -IC:\home\runner\_work\TheRock\TheRock\rocm-systems\shared\amdgpu-windows-interop\sc\HSAIL\ext\libamdhsacode\..\..\hsail-tools\libHSAIL -external:IB:\build\compiler\amd-comgr\dist\include -external:W0 /DWIN32 /D_WINDOWS /EHsc /DWIN32 /D_WINDOWS  /EHsc /O2 /Ob2 /DNDEBUG -std:c++20 -MD /wd4267 /wd4244 /wd4996 /MT /showIncludes /Forocclr\CMakeFiles\rocclr.dir\device\pal\palubercapturemgr.cpp.obj /Fdrocclr\CMakeFiles\rocclr.dir\rocclr.pdb /FS -c C:\home\runner\_work\TheRock\TheRock\rocm-systems\projects\clr\rocclr\device\pal\palubercapturemgr.cpp
2025-10-25T00:10:27.1718969Z [hip-clr] cl : Command line warning D9025 : overriding '/MD' with '/MT'
2025-10-25T00:10:27.1719698Z [hip-clr] C:\home\runner\_work\TheRock\TheRock\rocm-systems\projects\clr\rocclr\device\pal\palubercapturemgr.cpp(151): error C2039: 'RegisterTraceStateChangeCallback': is not a member of 'GpuUtil::TraceSession'
2025-10-25T00:10:27.1720577Z [hip-clr] C:\home\runner\_work\TheRock\TheRock\rocm-systems\shared\amdgpu-windows-interop\pal\inc\gpuUtil\palTraceSession.h(372): note: see declaration of 'GpuUtil::TraceSession'
2025-10-25T00:10:27.1721436Z [hip-clr] C:\home\runner\_work\TheRock\TheRock\rocm-systems\projects\clr\rocclr\device\pal\palubercapturemgr.cpp(194): error C2039: 'UnregisterTraceStateChangeCallback': is not a member of 'GpuUtil::TraceSession'
2025-10-25T00:10:27.1722288Z [hip-clr] C:\home\runner\_work\TheRock\TheRock\rocm-systems\shared\amdgpu-windows-interop\pal\inc\gpuUtil\palTraceSession.h(372): note: see declaration of 'GpuUtil::TraceSession'

```

**Comment by stellaraccident** [comment]
If you revert that patch in rocm-systems, send me the revert and I'll approve it.

**Comment by lamikr** [comment]
There seems to be more problems than only this one in the romc-systems libraries bump and I need to investigate more. I did just in case 2 builds on my local machine:

1) Latest therock --> This build fine
2) latest therock + rocm-systems bump + ClPrint fix mentioned above + hsail-support-revert patch
--> This  is still failing to build breaking hipDNN from rocm-libraries at least on my machine for following:
(hipDNN on current therock on master builds just fine)

```
[hipDNN configure] -- The HIP compiler identification is unknown
[hipDNN configure] CMake Error at /usr/share/cmake-3.28/Modules/CMakeDetermineHIPCompiler.cmake:174 (message):
[hipDNN configure]   Failed to find ROCm root directory.
[hipDNN configure] Call Stack (most recent call first):
[hipDNN configure]   sdk/tests/CMakeLists.txt:14 (enable_language)
[hipDNN configure] 
[hipDNN configure] 
[hipDNN configure] -- Configuring incomplete, errors occurred!
[hipDNN configure FAILED WITH CODE 1 in 15 seconds]

```

**Comment by stellaraccident** [comment]
> There seems to be more problems than only this one in the romc-systems libraries bump and I need to investigate more. I did just in case 2 builds on my local machine:
> 
> 1. Latest therock --> This build fine
> 2. latest therock + rocm-systems bump + ClPrint fix mentioned above + hsail-support-revert patch
>    --> This  is still failing to build breaking hipDNN from rocm-libraries at least on my machine for following:
>    (hipDNN on current therock on master builds just fine)
> 
> ```
> [hipDNN configure] -- The HIP compiler identification is unknown
> [hipDNN configure] CMake Error at /usr/share/cmake-3.28/Modules/CMakeDetermineHIPCompiler.cmake:174 (message):
> [hipDNN configure]   Failed to find ROCm root directory.
> [hipDNN configure] Call Stack (most recent call first):
> [hipDNN configure]   sdk/tests/CMakeLists.txt:14 (enable_language)
> [hipDNN configure] 
> [hipDNN configure] 
> [hipDNN configure] -- Configuring incomplete, errors occurred!
> [hipDNN configure FAILED WITH CODE 1 in 15 seconds]
> ```

Hipdnn is still experimental. You can disable it and let the team fix it. It shouldn't need to be probing for a rocm root.

**Comment by lamikr** [comment]
Okl, I will get that done during the weekend. I just checked that the db949445c3b513372f0bac5c5404521392c373f0 from rocm-systems still build ok.

**Comment by lamikr** [comment]
Reverting couple of batches fixed the linux builds, windows builds are stil failing on palubercapturemgr.cpp which is part of the clr even when I reverted one patch applied to it. 

I have not send the revert of all required patches to upstream because I have tried to figure what's needed by doing the CI builds first. On my own linux machine the builds are also passing with these patches reverted.

CI AI suggestion for the fix.

```
The build log shows errors during the compilation of palubercapturemgr.cpp:
Code

error C2039: 'RegisterTraceStateChangeCallback': is not a member of 'GpuUtil::TraceSession'
error C2039: 'UnregisterTraceStateChangeCallback': is not a member of 'GpuUtil::TraceSession'

This means the code in palubercapturemgr.cpp is trying to use methods (RegisterTraceStateChangeCallback, UnregisterTraceStateChangeCallback) that do not exist in GpuUtil::TraceSession, as defined in palTraceSession.h.
Solution

You need to update palubercapturemgr.cpp so it does not use those methods, or update the GpuUtil::TraceSession class in palTraceSession.h to add these methods if they should exist.
1. If these methods are no longer supported in GpuUtil::TraceSession:

Remove or replace their usage in palubercapturemgr.cpp:
C++

// Remove or comment out calls like:
traceSession.RegisterTraceStateChangeCallback(...);
traceSession.UnregisterTraceStateChangeCallback(...);

// If equivalent functionality is needed, check for updated APIs in palTraceSession.h

2. If these methods should exist:

Add their declarations and implementations to GpuUtil::TraceSession in palTraceSession.h and its related source file.

For example, in palTraceSession.h:
C++

class TraceSession {
    // ...
    void RegisterTraceStateChangeCallback(/* params */);
    void UnregisterTraceStateChangeCallback(/* params */);
    // ...
};

And implement in the corresponding .cpp file.
3. Check for API updates

Examine recent changes in the ROCm/Pal codebase for API changes. If there are replacement methods or new callback registration mechanisms, update palubercapturemgr.cpp to use the new API.
Code Suggestion Example

If removing is acceptable:
C++

// In palubercapturemgr.cpp
// Comment out or delete the following lines:
traceSession.RegisterTraceStateChangeCallback(...);
traceSession.UnregisterTraceStateChangeCallback(...);
```

**Comment by lamikr** [comment]
This PR can be dropped, I had another CI build running in parellel on

    https://github.com/ROCm/TheRock/pull/1943 

and that got merged. (I saved one patch revert)
