### ISSUE TITLE
[Issue] Windows 'nightly' PyTorch builds are failing with `Syntax error in cmake code at ... torch_hip_generated_FractionalMaxPool3d.hip.obj.cmake`

### ISSUE THREAD

**Issue by chiranjeevipattigidi** [ROCm/TheRock#2628]
**Run:** https://github.com/ROCm/TheRock/actions/runs/20329625718
**Python version:**   `3.11 , 3.12, 3.13`
**Pytorch Version:** `nightly`
#### Jobs:
- https://github.com/ROCm/TheRock/actions/runs/20329625718/job/58401728777
- https://github.com/ROCm/TheRock/actions/runs/20329625718/job/58401728765
- https://github.com/ROCm/TheRock/actions/runs/20329625718/job/58401728801

issue commit from pytorch nightly branch: https://github.com/pytorch/pytorch/commit/0a76f9da75271889c2718bf2b9387f70016d80d8

```

2025-12-18T08:29:41.4664861Z [6637/7085] Building HIPCC object caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_FractionalMaxPool3d.hip.obj
2025-12-18T08:29:41.4667120Z FAILED: [code=1] caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_FractionalMaxPool3d.hip.obj B:/src/torch/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_FractionalMaxPool3d.hip.obj 
2025-12-18T08:29:41.4671850Z C:\Windows\system32\cmd.exe /C "cd /D B:\src\torch\build\caffe2\CMakeFiles\torch_hip.dir\__\aten\src\ATen\native\hip && C:\home\runner\_work\_tool\Python\3.11.9\x64\Lib\site-packages\cmake\data\bin\cmake.exe -E make_directory B:/src/torch/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/. && C:\home\runner\_work\_tool\Python\3.11.9\x64\Lib\site-packages\cmake\data\bin\cmake.exe -D verbose:BOOL=OFF -D build_configuration:STRING=RELEASE -D generated_file:STRING=B:/src/torch/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/./torch_hip_generated_FractionalMaxPool3d.hip.obj -P B:/src/torch/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_FractionalMaxPool3d.hip.obj.cmake"
2025-12-18T08:29:41.4675104Z CMake Error at torch_hip_generated_FractionalMaxPool3d.hip.obj.cmake:53 (set):
2025-12-18T08:29:41.4675552Z   Syntax error in cmake code at
2025-12-18T08:29:41.4675727Z 
2025-12-18T08:29:41.4676281Z     B:/src/torch/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_FractionalMaxPool3d.hip.obj.cmake:53
2025-12-18T08:29:41.4676940Z 
2025-12-18T08:29:41.4677033Z   when parsing string
2025-12-18T08:29:41.4677178Z 
2025-12-18T08:29:41.4677967Z     --offload-compress;--rocm-device-lib-path=C:\home\runner\_work\_tool\Python\3.11.9\x64\Lib\site-packages\_rocm_sdk_devel\lib\llvm\amdgcn\bitcode;-fclang-abi-compat=17;-DUSE_ROCM
2025-12-18T08:29:41.4679611Z 
2025-12-18T08:29:41.4679724Z   Invalid character escape '\h'.
2025-12-18T08:29:41.4679928Z 
2025-12-18T08:29:41.4679934Z 
2025-12-18T08:29:41.5705487Z [6638/7085] Building HIPCC object caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_FusedAdamKernel.hip.obj
2025-12-18T08:29:41.5738723Z FAILED: [code=1] caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_FusedAdamKernel.hip.obj B:/src/torch/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_FusedAdamKernel.hip.obj 
2025-12-18T08:29:41.5744622Z C:\Windows\system32\cmd.exe /C "cd /D B:\src\torch\build\caffe2\CMakeFiles\torch_hip.dir\__\aten\src\ATen\native\hip && C:\home\runner\_work\_tool\Python\3.11.9\x64\Lib\site-packages\cmake\data\bin\cmake.exe -E make_directory 
```

**Comment by amd-chiranjeevi** [comment]
other gfx builds like (gfx120x) https://github.com/ROCm/TheRock/actions/runs/20328980060 from windows pytorch were triggered and checkout to previous commit https://github.com/pytorch/pytorch/commit/0bc5144aee9ee503ed74939a413b5fa0b04de315

**Comment by ScottTodd** [comment]
Culprit: https://github.com/pytorch/pytorch/commit/53319ff9e33e8b6cedde0af634571366cb043817. Commenting on the PR.

**Comment by ScottTodd** [comment]
Commented at https://github.com/pytorch/pytorch/pull/168377#pullrequestreview-3593717272

**Comment by amd-chiranjeevi** [comment]
seems failure are with different kind of syntax errors
- https://github.com/ROCm/TheRock/actions/runs/20480539415/job/58853043127
- https://github.com/ROCm/TheRock/actions/runs/20481052096/job/58854416206
```

2025-12-24T07:59:45.0221059Z   Run Build Command(s): C:/ProgramData/chocolatey/bin/ninja.exe -v cmTC_e527c
2025-12-24T07:59:45.0221257Z 
2025-12-24T07:59:45.0221318Z   [1/2]
2025-12-24T07:59:45.0221577Z   C:\home\runner\_work\_tool\Python\3.11.9\x64\Lib\site-packages\_rocm_sdk_devel\lib\llvm\bin\clang-cl.exe
2025-12-24T07:59:45.0221959Z   /nologo -D_MBCS /DWIN32 /D_WINDOWS /bigobj -Xclang -fopenmp=libiomp5 /Ob0
2025-12-24T07:59:45.0222221Z   /Od /RTC1 /bigobj -MDd -Z7 /showIncludes
2025-12-24T07:59:45.0222440Z   /FoCMakeFiles\cmTC_e527c.dir\OpenMPTryFlag.c.obj
2025-12-24T07:59:45.0222647Z   /FdCMakeFiles\cmTC_e527c.dir\ -c --
2025-12-24T07:59:45.0222875Z   B:\src\torch\build\CMakeFiles\FindOpenMP\OpenMPTryFlag.c
2025-12-24T07:59:45.0223036Z 
2025-12-24T07:59:45.0223158Z   FAILED: [code=1] CMakeFiles/cmTC_e527c.dir/OpenMPTryFlag.c.obj 
2025-12-24T07:59:45.0223328Z 
2025-12-24T07:59:45.0223378Z   
2025-12-24T07:59:45.0223628Z   C:\home\runner\_work\_tool\Python\3.11.9\x64\Lib\site-packages\_rocm_sdk_devel\lib\llvm\bin\clang-cl.exe
2025-12-24T07:59:45.0223993Z   /nologo -D_MBCS /DWIN32 /D_WINDOWS /bigobj -Xclang -fopenmp=libiomp5 /Ob0
2025-12-24T07:59:45.0224264Z   /Od /RTC1 /bigobj -MDd -Z7 /showIncludes
2025-12-24T07:59:45.0224479Z   /FoCMakeFiles\cmTC_e527c.dir\OpenMPTryFlag.c.obj
2025-12-24T07:59:45.0224682Z   /FdCMakeFiles\cmTC_e527c.dir\ -c --
2025-12-24T07:59:45.0224893Z   B:\src\torch\build\CMakeFiles\FindOpenMP\OpenMPTryFlag.c
2025-12-24T07:59:45.0225044Z 
2025-12-24T07:59:45.0225175Z   B:\src\torch\build\CMakeFiles\FindOpenMP\OpenMPTryFlag.c(8,3): error: use
2025-12-24T07:59:45.0225447Z   of undeclared identifier 'breaks_on_purpose'
2025-12-24T07:59:45.0225580Z 
2025-12-24T07:59:45.0225644Z       8 |   breaks_on_purpose
2025-12-24T07:59:45.0225795Z         |   ^~~~~~~~~~~~~~~~~
2025-12-24T07:59:45.0225886Z 
2025-12-24T07:59:45.0225946Z   1 error generated.
2025-12-24T07:59:45.0226030Z 
2025-12-24T07:59:45.0226100Z   ninja: build stopped: subcommand failed.
```

**Comment by ScottTodd** [comment]
The PyTorch build failures here look to be fixed by https://github.com/pytorch/pytorch/commit/402153d95aa20f8c1b625b11a99440e5fc38004f, though torchaudio is newly failing to build. Will check if we have an issue for that already and follow-up.
