### ISSUE TITLE
[Issue]: roctracer build errors on Ubuntu 24.04

### ISSUE THREAD

**Issue by b-sumner** [ROCm/TheRock#3221]
### Problem Description

I'm trying to build on Ubuntu 24.04 with the following command.  My repo is up-to-date as of a few hours ago.

cmake \
  -B build \
  -GNinja \
  -DTHEROCK_ENABLE_COMM_LIBS=OFF \
  -DTHEROCK_ENABLE_MATH_LIBS=OFF \
  -DTHEROCK_ENABLE_ML_LIBS=OFF \
  -DTHEROCK_ENABLE_MPI=OFF \
  -DTHEROCK_AMDGPU_FAMILIES=gfx1200 \
  -DTHEROCK_BUILD_TESTING=OFF \
  .
cmake --build build

I needed the BUILD_TESTING=OFF to bypass a failure in rocrtest where a fix is in progress.  But then the build fails later in rocrtracer.

### Operating System

Ubuntu 24.04.3

### CPU

AMD Ryzen Threadripper PRO 5965WX 24-Cores

### GPU

None, build time issue

### ROCm Version

None

**Comment by ScottTodd** [comment]
> But then the build fails later in rocrtracer.

Can you share the logs (full or just a snippet)? There should be log files in `build/logs/`, and I think the roctracer logs should be small enough to fit in https://gist.github.com/ (8KB)

Here are some successful build logs for roctracer: https://therock-ci-artifacts.s3.amazonaws.com/21625000463-linux/logs/gfx1151/roctracer_build.log from
* https://therock-ci-artifacts.s3.amazonaws.com/21625000463-linux/logs/gfx1151/index.html
* https://github.com/ROCm/TheRock/actions/runs/21625000463
* https://github.com/ROCm/TheRock/commit/45d3ea3dd2ecc8d5627630c57baf37a54ba276a8

**Comment by b-sumner** [comment]
Thanks.  Here is the end of the log where the error shows up:

0.3     -- Configuring done (0.3s)
0.3     -- Generating done (0.0s)
0.3     -- Build files have been written to: /git/therock/build/profiler/roctracer/build
0.3     [1/9] cd /git/therock/build/profiler/roctracer/build && /usr/bin/cmake -E rm -f /git/therock/build/profiler/roctracer/stamp/stage.stamp
0.4     [2/9] Linking HIP executable test/activity_and_callback
0.4     [3/9] Linking HIP executable test/MatrixTranspose
0.4     [4/9] Linking HIP executable test/MatrixTranspose_mgpu
0.4     [5/9] Linking HIP executable test/MatrixTranspose_hipaact_test
0.4     [6/9] Linking HIP executable test/MatrixTranspose_test
0.4     [7/9] Linking HIP executable test/multi_pool_activities
0.5     [8/9] Building HIPCC object test/CMakeFiles/roctx_test.dir/app/roctx_test_generated_roctx_test.cpp.o
0.5     FAILED: test/CMakeFiles/roctx_test.dir/app/roctx_test_generated_roctx_test.cpp.o /git/therock/build/profiler/roctracer/build/test/CMakeFiles/roctx_test.dir/app/roctx_test_generated_roctx_test.cpp.o
0.5     cd /git/therock/build/profiler/roctracer/build/test/CMakeFiles/roctx_test.dir/app && /usr/bin/cmake -E make_directory /git/therock/build/profiler/roctracer/build/test/CMakeFiles/roctx_test.dir/app/. && /usr/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=RELEASE -D generated_file:STRING=/git/therock/build/profiler/roctracer/build/test/CMakeFiles/roctx_test.dir/app/./roctx_test_generated_roctx_test.cpp.o -P /git/therock/build/profiler/roctracer/build/test/CMakeFiles/roctx_test.dir/app/roctx_test_generated_roctx_test.cpp.o.cmake
0.5     /git/therock/rocm-systems/projects/roctracer/test/app/roctx_test.cpp:21:10: fatal error: 'hip/hip_runtime.h' file not found
0.5        21 | #include <hip/hip_runtime.h>
0.5           |          ^~~~~~~~~~~~~~~~~~~
0.5     1 error generated when compiling for host.
0.5     failed to execute:/git/therock/build/core/clr/dist/lib/llvm/bin/clang++  --offload-arch=gfx1101 --cuda-host-only -O3  -M -x hip /git/therock/rocm-systems/projects/roctracer/test/app/roctx_test.cpp -o "/git/therock/build/profiler/roctracer/build/test/CMakeFiles/roctx_test.dir/app/roctx_test_generated_roctx_test.cpp.o.depend.pre" -DAMD_INTERNAL_BUILD -DHIP_TEST=0 -D__HIP_PLATFORM_AMD__ -DAMD_INTERNAL_BUILD -I/git/therock/rocm-systems/projects/roctracer/inc
0.5     CMake Error at roctx_test_generated_roctx_test.cpp.o.cmake:146 (message):
0.5       Error generating
0.5       /git/therock/build/profiler/roctracer/build/test/CMakeFiles/roctx_test.dir/app/./roctx_test_generated_roctx_test.cpp.o
0.5
0.5
0.5     ninja: build stopped: subcommand failed.
END     1770140825.1210868      0.5015556812286377      1

**Comment by stellaraccident** [comment]
## Investigation Summary

Tested a similar configuration on Ubuntu 25.04 with GCC 14. The build completed successfully after addressing two separate GCC 14 compatibility issues:

### Issues discovered during investigation:

1. **ncurses wide character support broken** (#3223, fixed in #3224)
   - ncurses autoconf incorrectly defines `pid_t` as `int` on modern glibc systems
   - This conflicts with glibc's typedef and breaks wchar_t detection
   - Result: `--enable-widec` silently fails, causing `cchar_t` to be undefined
   - Fix: Override autoconf's detection with `ac_cv_type_pid_t=yes`

2. **rocprofiler-systems missing includes** (#3227)
   - GCC 14 is stricter about transitive includes
   - `logger.hpp` missing `#include <algorithm>` and `#include <array>`
   - Error: `'any_of' is not a member of 'std'`

### Regarding the roctracer error in this issue:

Looking at the error in the comments:
```
fatal error: 'hip/hip_runtime.h' file not found
```

This is happening during roctracer **test** compilation (`roctx_test.cpp`). The clang++ invocation shows it's missing `-I` flags for the HIP include directory. The command line only has:
```
-I/git/therock/rocm-systems/projects/roctracer/inc
```

But needs something like:
```
-I<build>/core/clr/dist/include
```

This appears to be a CMake configuration issue where the roctracer test targets aren't properly linking to or getting include paths from the HIP runtime target. The `BUILD_TESTING=OFF` workaround avoids this by skipping test compilation entirely.

The fix would be in the roctracer CMakeLists.txt to ensure test executables have proper dependencies on HIP targets to inherit include directories.

**Comment by stellaraccident** [comment]
@ammarwa and @jrmadsen who I was discussing this offline (wrt when we can just drop roctracer)

**Comment by stellaraccident** [comment]
**Update:** Re-tested with `THEROCK_BUILD_TESTING=ON` and roctracer tests build successfully, including `roctx_test`:

```
[27/54] Building HIPCC object test/CMakeFiles/roctx_test.dir/app/roctx_test_generated_roctx_test.cpp.o
[28/54] Linking HIP executable test/roctx_test
...
[roctracer SUCCEEDED in 20 seconds]
```

The `hip/hip_runtime.h` not found error does not reproduce on current main. The issue may have been:
- A stale build state (try clean rebuild: `ninja roctracer+expunge && ninja roctracer+build`)
- A race condition that has since been addressed
- Fixed in a more recent commit

It may also be an environmental issue: these older projects can get easily confused when there is already a ROCm installed at /opt/rocm.

@b-sumner Can you try a fresh build on current main to see if the issue persists?

**Comment by b-sumner** [comment]
I tried a fresh build and am still seeing the

0.4     /git/therock/rocm-systems/projects/roctracer/test/app/roctx_test.cpp:21:10: fatal error: 'hip/hip_runtime.h' file not found
0.4        21 | #include <hip/hip_runtime.h>

I do have an /opt/rocm/ directory on my system.  Should I try renaming that before building?

**Comment by b-sumner** [comment]
@stellaraccident how did your build get past the rocrtst issue?  #3200 didn't land.  I have to use BUILD_TESTING=OFF to get past rocrtst and then hit the roctracer issue.

**Comment by b-sumner** [comment]
I just updated the repo and removed the build directory and ran the same cmake commands in the problem description.  The build is still stopping in roctracer with the same fatal error: 'hip/hip_runtime.h' file not found.  This was again with -DTHEROCK_BUILD_TESTING=OFF.  It seems like this test is still being built:

0.4     [11/54] Building HIPCC object test/CMakeFiles/roctx_test.dir/app/roctx_test_generated_roctx_test.cpp.o
0.4     FAILED: test/CMakeFiles/roctx_test.dir/app/roctx_test_generated_roctx_test.cpp.o /git/therock/build/profiler/roctracer/build/test/CMakeFiles/roctx_test.dir/app/roctx_test_generated_roctx_test.cpp.o
0.4     cd /git/therock/build/profiler/roctracer/build/test/CMakeFiles/roctx_test.dir/app && /usr/bin/cmake -E make_directory /git/therock/build/profiler/roctracer/build/test/CMakeFiles/roctx_test.dir/app/. && /usr/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=RELEASE -D generated_file:STRING=/git/therock/build/profiler/roctracer/build/test/CMakeFiles/roctx_test.dir/app/./roctx_test_generated_roctx_test.cpp.o -P /git/therock/build/profiler/roctracer/build/test/CMakeFiles/roctx_test.dir/app/roctx_test_generated_roctx_test.cpp.o.cmake
0.4     /git/therock/rocm-systems/projects/roctracer/test/app/roctx_test.cpp:21:10: fatal error: 'hip/hip_runtime.h' file not found
0.4        21 | #include <hip/hip_runtime.h>
0.4           |          ^~~~~~~~~~~~~~~~~~~
0.4     1 error generated when compiling for host.
0.4     failed to execute:/git/therock/build/core/clr/dist/lib/llvm/bin/clang++  --offload-arch=gfx1101 --cuda-host-only -O3  -M -x hip /data/bsumner/git/therock/rocm-systems/projects/roctracer/test/app/roctx_test.cpp -o "/git/therock/build/profiler/roctracer/build/test/CMakeFiles/roctx_test.dir/app/roctx_test_generated_roctx_test.cpp.o.depend.pre" -DAMD_INTERNAL_BUILD -DHIP_TEST=0 -D__HIP_PLATFORM_AMD__ -DAMD_INTERNAL_BUILD -I/git/therock/rocm-systems/projects/roctracer/inc

**Comment by b-sumner** [comment]
Adding  -DTHEROCK_ENABLE_PROFILER=OFF didn't avoid the issue.

**Comment by b-sumner** [comment]
I asked cursor to examine this failure.   This is what it had to say:

[19 tools called]

The build failure is the `roctx_test` HIP compilation step missing `hip/hip_runtime.h`. The root cause is a mismatch between how the top-level super-project isolates ROCm/HIP discovery and how the roctracer *tests* locate HIP.

What’s happening, end-to-end:

- The super-project **unsets** `ROCM_PATH`/`HIP_PATH` for all subproject configure/build commands to prevent accidental use of system installs.  
```693:696:/data/bsumner/git/therock/cmake/therock_subproject.cmake
  list(APPEND _build_env_pairs "--unset=ROCM_PATH")
  list(APPEND _build_env_pairs "--unset=ROCM_DIR")
  list(APPEND _build_env_pairs "--unset=HIP_PATH")
  list(APPEND _build_env_pairs "--unset=HIP_DIR")
```

- In `rocm-systems/projects/roctracer/CMakeLists.txt`, `ROCM_PATH` is **not** overridden by the super-project, so it defaults to `/opt/rocm` and is used for the CONFIG package lookup.  
```37:59:/data/bsumner/git/therock/rocm-systems/projects/roctracer/CMakeLists.txt
if(NOT DEFINED ROCM_PATH)
    set(ROCM_PATH "/opt/rocm"  CACHE STRING "Default ROCM installation directory")
endif()
...
find_package(hsa-runtime64 REQUIRED CONFIG PATHS ${ROCM_PATH})
find_package(HIP REQUIRED CONFIG PATHS ${ROCM_PATH})
```

- In `roctracer/test/CMakeLists.txt`, the tests **explicitly** use the *MODULE* `FindHIP.cmake`, and also set `CMAKE_MODULE_PATH` to `${ROCM_PATH}/lib/cmake/hip` (so `/opt/rocm/lib/cmake/hip`), and `HIP_ROOT_DIR` to `${ROCM_PATH}/bin`. This bypasses the super-project’s CONFIG-based HIP package and reverts to the default `/opt/rocm` logic.  
```30:35:/data/bsumner/git/therock/rocm-systems/projects/roctracer/test/CMakeLists.txt
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${ROCM_PATH}/lib/cmake/hip")
set(CMAKE_HIP_ARCHITECTURES OFF)
if(DEFINED ROCM_PATH)
    set(HIP_ROOT_DIR "${ROCM_PATH}/bin")
endif()
find_package(HIP REQUIRED MODULE)
```

- The generated HIP compilation script shows that `HIP_HIPCC_INCLUDE_ARGS` only contains the roctracer include directory (no HIP include path), which is why `hip/hip_runtime.h` can’t be found.  
```68:70:/data/bsumner/git/therock/build/profiler/roctracer/build/test/CMakeFiles/roctx_test.dir/app/roctx_test_generated_roctx_test.cpp.o.cmake
#Needed to bring the HIP_HIPCC_INCLUDE_ARGS variable in scope
set(HIP_HIPCC_INCLUDE_ARGS -I/data/bsumner/git/therock/rocm-systems/projects/roctracer/inc) # list
```

So the interaction problem is:

1) The super-project unsets env discovery and expects subprojects to resolve dependencies via the *provided* packages (CONFIG).  
2) `roctracer/test` forces the *MODULE* `FindHIP` from `/opt/rocm`, which does **not** get the in-tree HIP include path and yields an empty `HIP_HIPCC_INCLUDE_ARGS` (except for the project include).  
3) `hipcc` comes from the in-tree build (`build/core/clr/dist/bin/hipcc`), but the headers are not on the include path → compile fails.

### Likely Fix Direction (if you want to adjust)
- **Prefer CONFIG-based HIP everywhere** in roctracer, including tests. That means removing `find_package(HIP REQUIRED MODULE)` and using the CONFIG package (or use targets/variables exposed by the CONFIG package).
- Alternatively, **set `ROCM_PATH`** in the subproject init (or in roctracer test CMake) to the in-tree dist root (e.g. `${THEROCK_BINARY_DIR}/core/clr/dist`) so that the module lookup and `HIP_ROOT_DIR` point to the in-tree HIP install.

If you want, I can propose a small patch to make roctracer tests respect the super-project’s HIP package (CONFIG), which will add the proper HIP include path and avoid this failure.
