### ISSUE TITLE
[Issue]: unsloth compatiblity issue with torch therock windows

### ISSUE THREAD

**Issue by lihaofd** [ROCm/TheRock#2008]
### Problem Description

780M iGPU on windows
python -m pip install   --index-url https://rocm.nightlies.amd.com/v2/gfx110X-all/   "rocm[libraries,devel]"
python -m pip install   --index-url https://rocm.nightlies.amd.com/v2/gfx110X-all/   --pre torch torchaudio torchvision

https://docs.unsloth.ai/get-started/install-and-update/amd
pip install --no-deps unsloth unsloth-zoo
pip install --no-deps git+https://github.com/unslothai/unsloth-zoo.git
pip install "unsloth[amd] @ git+https://github.com/unslothai/unsloth"

https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/GPT_OSS_MXFP4_(20B)-Inference.ipynb

from unsloth import FastLanguageModel 
always shows 
AttributeError: module 'torch.distributed' has no attribute 'is_initialized'

### Operating System

windows 11

### CPU

7840U

### GPU

780M

### ROCm Version

2.10.0a0+rocm7.10.0a20251031

**Comment by astrelsky** [comment]
Same problem, or similar, trying to use amd quark.

**Comment by andyluo7** [comment]
Can you try it on WSL?

**Comment by lihaofd** [comment]
wsl have issues reported before - https://github.com/ROCm/TheRock/issues/690#issuecomment-2911051236
I can also reproduce 
WSL environment detected.
hsa api call failure at: /therock/src/rocm-systems/projects/rocminfo/rocminfo.cc:1324

**Comment by adityas-amd** [comment]
Yes, this is the same underlying known limitation on Windows ROCm limitation as #[1179](https://github.com/orgs/ROCm/projects/99/views/3?sliceBy%5Bvalue%5D=adityas-amd&pane=issue&itemId=129652720&issue=ROCm%7CTheRock%7C1179). The current Windows ROCm (“TheRock”) PyTorch builds do not enable torch.distributed (Gloo is Linux-only in these builds, and RCCL is not supported on Windows yet), so common APIs like dist.is_initialized and dist.init_process_group are missing. 
If you want to test Unsloth with AMD acceleration right now, please use Linux + ROCm where Unsloth is tested and torch.distributed works.
On Windows, Unsloth support is limited. Please wait until RCCL (and/or a Windows-compatible distributed backend) is supported in the TheRock builds.

**Comment by 0xDELUXA** [comment]
@lihaofd this issue is resolved by https://github.com/ROCm/TheRock/pull/5694. Confirmed working on torch `2.12.0+rocm7.14.0a20260620`.
